

stages:
  data_ingestion:
    cmd: python src/CatDogClassification/pipeline/Data_ingestion_pipeline.py
    deps:
      - src/CatDogClassification/pipeline/Data_ingestion_pipeline.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/cat_dog/train

  prepare_base_model:
    cmd: python src/CatDogClassification/pipeline/Prepare_base_model_pipeline.py
    deps:
      - src/CatDogClassification/pipeline/Prepare_base_model_pipeline.py
      - config/config.yaml
    params:
      - INPUT_SHAPE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/CatDogClassification/pipeline/Training_pipeline.py
    deps:
      - src/CatDogClassification/pipeline/Training_pipeline.py
      - config/config.yaml
      - artifacts/data_ingestion/cat_dog/train
      - artifacts/prepare_base_model
    params:
      - INPUT_SHAPE
      - EPOCHS
      - BATCH_SIZE
    outs:
      - artifacts/training_model/model.h5